String.toLocaleString({
	"en-US": {
		"%nav_acerca": "About",
		"%nav_cultura": "Culture",
		"%nav_sitemap": "Sitemap",
		"%nav_contacto": "Contact Us",
		"%nav_educacion": "Education",
		"%nav_educacion_sobre": "About Education",
		"%nav_educacion_temas": "Subjects",
		"%nav_educacion_mundo": "World Education",
		"%nav_educacion_eventos": "Events",
		"%nav_educacion_redes": "Networks",
		"%nav_educacion_asociados": "Associates",
		"%nav_ciencias": "Sciences",
		"%nav_ciencias_naturales": "Naturals",
		"%nav_ciencias_somos": "Who are we?",
		"%nav_ciencias_trabajamos": "How do we work?",
		"%nav_ciencias_subdirectora": "General Subdirectory",
		"%footer_title": "Knowledge for life",
		"%footer_acerca": "About us /",
		"%footer_educacion": "Education /",
		"%footer_ciencias": "Sciencies /",
		"%footer_cultura": "Culture /",
		"%footer_sitemap": "Sitemap /",
		"%footer_contacto": "Contact us",
		"%derechos": "All rights reserved",
		"%donador": "Become a donator",
		"%donacion": "Make a donation",
		"%voluntario": "Become a volunteer",
	},
	"de": {
		"%nav_acerca": "Über uns",
		"%nav_cultura": "Kultur",
		"%nav_sitemap": "Sitemap",
		"%nav_contacto": "Kontaktiere uns",
		"%nav_educacion": "Ausbildung",
		"%nav_educacion_sobre": "Über Bildung",
		"%nav_educacion_temas": "Fächer",
		"%nav_educacion_mundo": "Weltbildungs",
		"%nav_educacion_eventos": "Veranstaltungen",
		"%nav_educacion_redes": "Networks",
		"%nav_educacion_asociados": "Assoziieren",
		"%nav_cultura": "Wissenschaften",
		"%nav_cultura_temas": "Naturwissenschaft",
		"%nav_cultura_comunidades": "Wer sind wir?",
		"%nav_cultura_eventos": "Wer sind wir?",
		"%nav_cultura_eventos": "Stellvertretender Generaldirektor",
		"%footer_title": "Wissen für das Leben",
		"%footer_acerca": "Über uns /",
		"%footer_educacion": "Ausbildung /",
		"%footer_ciencias": "Wissenschaften /",
		"%footer_cultura": "Kultur /",
		"%footer_sitemap": "Sitemap /",
		"%footer_contacto": "Kontaktiere uns",
		"%derechos": "Alle Rechte vorbehalten",
		"%donador": "Werden Sie ein Donator",
		"%donacion": "Eine Spende an das Programm",
		"%voluntario": "zu einem Freiwilligen",
	}
});
